if(NOT WIN32)
  string(ASCII 27 Esc)
  set(ColourReset "${Esc}[m")
  set(ColourBold  "${Esc}[1m")
  set(Red         "${Esc}[31m")
  set(Green       "${Esc}[32m")
  set(Yellow      "${Esc}[33m")
  set(Blue        "${Esc}[34m")
  set(Magenta     "${Esc}[35m")
  set(Cyan        "${Esc}[36m")
  set(White       "${Esc}[37m")
  set(BoldRed     "${Esc}[1;31m")
  set(BoldGreen   "${Esc}[1;32m")
  set(BoldYellow  "${Esc}[1;33m")
  set(BoldBlue    "${Esc}[1;34m")
  set(BoldMagenta "${Esc}[1;35m")
  set(BoldCyan    "${Esc}[1;36m")
  set(BoldWhite   "${Esc}[1;37m")
endif()

macro(fatal)
	message(FATAL_ERROR ${BoldRed}${ARGV0}${ColourReset})
endmacro()


macro(info)
	message(STATUS ${Magenta}${ARGV0}${ColourReset})
endmacro()


macro(find_program_on_host)
	if(${ARGC} LESS 1)
		message(FATAL_ERROR "find_program_on_host NAME [PATH]")
	endif()
	find_program(${ARGV0} ${ARGV0})
	if( ${${ARGV0}} STREQUAL ${ARGV0}-NOTFOUND )
		fatal("Can't find ${ARGV0}")
	else()
		info("find on ${${ARGV0}}")
	endif()
endmacro()

macro(include_guard)
	if(INCLUDED_${CMAKE_CURRENT_LIST_FILE})
		message("it is already include.(${CMAKE_CURRENT_LIST_FILE}")
		return()
	endif()
	set(INCLUDED_${CMAKE_CURRENT_LIST_FILE} TRUE)
endmacro()
